name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ”¹ Kodni yuklab olish
        uses: actions/checkout@v3

      - name: ðŸ”¹ Python oâ€˜rnatish
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: ðŸ”¹ Buildozer va kerakli paketlarni oâ€˜rnatish
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel python3-virtualenv
          pip install --upgrade pip
          pip install buildozer cython

      - name: ðŸ”¹ Android SDK/NDK kerakli fayllar
        run: |
          sudo apt install -y libltdl-dev libffi-dev libssl-dev
          sudo apt install -y adb

      - name: ðŸ”¹ APK yigâ€˜ish
        run: |
          buildozer -v android debug

      - name: ðŸ“¦ APK faylini yuklash (Artifact)
        uses: actions/upload-artifact@v3
        with:
          name: my-app
          path: bin/*.apk
